
services:

  postgres:
    image: postgres-listen-notify:1
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres: